#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-05-02 17:58:28.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("githubRepo() works", {

  f <- kwb.package:::githubRepo

  expect_error(
    f()
    # Argument "github_user" fehlt (ohne Standardwert)
  )

})
