#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-05-02 18:06:07.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("installPackageIfRequired() works", {

  f <- kwb.package:::installPackageIfRequired

  expect_error(
    f()
    # Argument "packageName" fehlt (ohne Standardwert)
  )

})
