#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-05-02 17:58:26.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("getCranPackageDatabase() works", {

  f <- kwb.package::getCranPackageDatabase

  expect_error(
    f()
    # No such element in list 'urls':
# - 'cran_packages'
# Available elements (sorted):
# - 'cached_desc'
# - 'cran'
# - 'cran_archive'
# - 'cran_archive_file'
# - 'cran_contrib'
# - 'cran_package'
# - 'cran_package_file'
# - 'cran_rstudio'
# - 'github_api'
# - 'github_desc'
# - 'github_raw'
# - 'github_releases'
# - 'github_tags'
# - 'mran_snapshot'
# - 'package_filename'
# 
  )

})
