#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-05-02 17:58:25.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("getLastVersionBefore() works", {

  f <- kwb.package:::getLastVersionBefore

  expect_error(
    f()
    # Argument "version_dates" fehlt (ohne Standardwert)
  )

})
