#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-05-02 18:06:14.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("exampleLinksAndNodes() works", {

  f <- kwb.package::exampleLinksAndNodes

  expect_error(
    f()
    # line 8 did not have 4 elements
  )

})
