#
# This file was generated by kwb.test::create_test_files(), 
# launched by hsonne on 2024-05-02 18:06:14.
# Please modify the dummy functions so that real cases are
# tested. Then, delete this comment.
#

test_that("plotSankeyNetwork() works", {

  f <- kwb.package::plotSankeyNetwork

  expect_error(
    f()
    # Argument "functionName" fehlt (ohne Standardwert)
  )

})
